# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f665ecacb8ebb0109bd7994468b79d14"
name = "nimblers"
handle = "nimblers"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

# GDPR Compliance Webhooks
[[webhooks.compliance]]
topic = "customers/data_request"
endpoint = "/shopify/privacy/customers-data-request"

[[webhooks.compliance]]
topic = "customers/redact"
endpoint = "/shopify/privacy/customers-data-erasure"

[[webhooks.compliance]]
topic = "shop/redact"
endpoint = "/shopify/privacy/shop-data-erasure"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
