export {
  AlertTriangle,
  ArrowRight,
  Bell,
  Check,
  CheckCircle2 as CheckCircle, // Alias for consistency if needed, or use directly
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  Copy,
  DownloadCloud,
  Edit3 as Edit,
  ExternalLink,
  Eye,
  EyeOff,
  Heart,
  Home,
  Info,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  MinusCircle,
  Moon,
  MoreHorizontal,
  PlusCircle,
  Search,
  Settings,
  ShoppingCart,
  Sun,
  Trash2 as Trash,
  UploadCloud,
  User,
  Users,
  X as Close,
  XCircle,
  // Add more icons as needed by the design system
} from "lucide-react";
